---
deployment:
  tasks:
    - export DEPLOYPATH=/home/luckbepo/test.lucky-victory.dev
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R * proto-css $DEPLOYPATH
    - /bin/cp -R * proto-images $DEPLOYPATH 